import express from "express";
import basketController from "../controllers/BasketController.js";
const basketRouter = new express.Router();
basketRouter.get('/', basketController.getOneAmount);
basketRouter.get('/bought', basketController.bought);
basketRouter.get('/reviewed', basketController.reviewed);
basketRouter.get('/orders', basketController.getOrders);
basketRouter.get('/orderContacts', basketController.getContacts);
basketRouter.get('/reviews', basketController.getReviews);
basketRouter.post('/review', basketController.addReview);
basketRouter.patch('/review', basketController.updateReview);
basketRouter.delete('/review', basketController.deleteReview);
basketRouter.post('/formBasketOrder', basketController.formBasketOrder);
basketRouter.post('/formFastOrder', basketController.formFastOrder);
basketRouter.delete('/clearOrders', basketController.clearOrders);
basketRouter.get('/:userId', basketController.getAll);
basketRouter.post('/', basketController.addItem);
basketRouter.delete('/', basketController.deleteItem);
export default basketRouter;