import express from "express";
import basketController from "../controllers/basketController.js";
const basketRouter = new express.Router();
basketRouter.get('/', basketController.getAll);
basketRouter.get('/amount', basketController.getOneAmount);
basketRouter.get('/getContacts', basketController.getContacts);
basketRouter.post('/', basketController.addItem);
basketRouter.delete('/', basketController.deleteItem);
basketRouter.get('/orders', basketController.getOrders);
basketRouter.post('/formOrder', basketController.formOrder);
basketRouter.delete('/clearOrders', basketController.clearOrders);
export default basketRouter;