import express from "express";
import basketController from "../controllers/basketController.js";
import httpMiddleware from "../middlewares/httpMiddleware.js";
const basketRouter = new express.Router();
basketRouter.get('/', httpMiddleware.isAuth, basketController.getAll);
basketRouter.get('/amount', httpMiddleware.isAuth, basketController.getOneAmount);
basketRouter.get('/getContacts', httpMiddleware.isAuth, basketController.getContacts);
basketRouter.post('/', httpMiddleware.isAuth, basketController.addItem);
basketRouter.delete('/', httpMiddleware.isAuth, basketController.deleteItem);
basketRouter.get('/orders', httpMiddleware.isAuth, basketController.getOrders);
basketRouter.post('/formOrder', httpMiddleware.isAuth, basketController.formOrder);
basketRouter.delete('/clearOrders', httpMiddleware.isAuth, basketController.clearOrders);
export default basketRouter;